const pantryItems = [
  { name: "Apples" },
  { name: "Bananas" },
  { name: "Oranges" },
  { name: "Lemons" },
  { name: "Strawberries" },
  { name: "Blueberries" },
  { name: "Pineapple" },
  { name: "Mango" },
  { name: "Grapes" },
  { name: "Avocado" },
  { name: "Potato" },
  { name: "Onions" },
  { name: "Tomato" },
  { name: "Garlic" },
  { name: "Bell Peppers" },
  { name: "Spinach" },
  { name: "Carrots" },
  { name: "Broccoli" },
  { name: "Mushrooms" },
  { name: "Zucchini" },
  { name: "Basil" },
  { name: "Parsley" },
  { name: "Thyme" },
  { name: "Rosemary" },
  { name: "Cilantro" },
  { name: "Cumin" },
  { name: "Turmeric" },
  { name: "Chili Powder" },
  { name: "Paprika" },
  { name: "Oregano" },
  { name: "Chicken" },
  { name: "Beef" },
  { name: "Pork" },
  { name: "Fish" },
  { name: "Eggs" },
  { name: "Tofu" },
  { name: "Lentils" },
  { name: "Chickpeas" },
  { name: "Black Beans" },
  { name: "Paneer" },
  { name: "Rice" },
  { name: "Quinoa" },
  { name: "Oats" },
  { name: "Barley" },
  { name: "Flour" },
  { name: "Pasta" },
  { name: "Bread" },
  { name: "Tortillas" },
  { name: "Couscous" },
  { name: "Polenta" },
  { name: "Milk" },
  { name: "Cheese" },
  { name: "Butter" },
  { name: "Yogurt" },
  { name: "Cream" },
  { name: "Sour Cream" },
  { name: "Olive Oil" },
  { name: "Vegetable Oil" },
  { name: "Soy Sauce" },
  { name: "Vinegar" },
  { name: "Mustard" },
  { name: "Ketchup" },
  { name: "Mayonnaise" },
  { name: "Hot Sauce" },
  { name: "Honey" },
  { name: "Peanut Butter" },
  { name: "Sugar" },
  { name: "Brown Sugar" },
  { name: "Salt" },
  { name: "Baking Powder" },
  { name: "Baking Soda" },
  { name: "Cocoa Powder" },
  { name: "Vanilla Extract" },
  { name: "Shrimp" },
  { name: "Crab" },
  { name: "Lobster" },
  { name: "Clams" },
  { name: "Squid" },
  { name: "Chocolate Chips" },
  { name: "Almonds" },
  { name: "Walnuts" },
  { name: "Cashews" },
  { name: "Sunflower Seeds" },
  { name: "Chia Seeds" },
  { name: "Flax Seeds" },
  { name: "Raisins" },
  { name: "Canned Tomato Sauce" },
  { name: "Coconut Milk" },
];
const dishes = [
  { name: "Sushi" },
  { name: "Pizza" },
  { name: "Tacos" },
  { name: "Ramen" },
  { name: "Paella" },
  { name: "Poutine" },
  { name: "Biryani" },
  { name: "Kimchi" },
  { name: "Croissant" },
  { name: "Shawarma" },
  { name: "Pho" },
  { name: "Goulash" },
  { name: "Falafel" },
  { name: "Ceviche" },
  { name: "Moussaka" },
  { name: "Lasagna" },
  { name: "Empanadas" },
  { name: "Dim Sum" },
  { name: "Bulgogi" },
  { name: "Arepas" },
  { name: "Baklava" },
  { name: "Pad Thai" },
  { name: "Jollof Rice" },
  { name: "Tagine" },
  { name: "Clam Chowder" },
  { name: "Churros" },
  { name: "Bibimbap" },
  { name: "Tiramisu" },
  { name: "Hummus" },
  { name: "Tamales" },
  { name: "Currywurst" },
  { name: "Pavlova" },
  { name: "Pierogi" },
  { name: "Ratatouille" },
  { name: "Chow Mein" },
  { name: "Crepes" },
  { name: "Pork Adobo" },
  { name: "Fish and Chips" },
  { name: "Vindaloo" },
  { name: "Gyoza" },
  { name: "Malai Kofta" },
  { name: "Cannoli" },
  { name: "Banh Mi" },
  { name: "Fettuccine Alfredo" },
  { name: "Samosa" },
  { name: "Okonomiyaki" },
  { name: "Khinkali" },
  { name: "Kebab" },
  { name: "Onigiri" },
  { name: "Stuffed Peppers" },
  { name: "Cottage Pie" },
  { name: "Manakish" },
  { name: "Pozole" },
  { name: "Feijoada" },
  { name: "Mochi" },
  { name: "Rendang" },
  { name: "Fajitas" },
  { name: "Aloo Gobi" },
  { name: "Shepherd’s Pie" },
  { name: "Pesto Pasta" },
  { name: "Spaghetti Carbonara" },
  { name: "Khao Pad" },
  { name: "Lobster Roll" },
  { name: "Zongzi" },
  { name: "Chimichurri Steak" },
  { name: "Eggs Benedict" },
  { name: "Shakshuka" },
  { name: "Tandoori Chicken" },
  { name: "Pierna de Cordero" },
  { name: "Gado-Gado" },
  { name: "Katsudon" },
  { name: "Vareniki" },
  { name: "Hot Pot" },
  { name: "Dal Tadka" },
  { name: "Satay" },
  { name: "Chilaquiles" },
  { name: "Steak Tartare" },
  { name: "Sauerbraten" },
  { name: "Boeuf Bourguignon" },
  { name: "Couscous" },
  { name: "Gumbo" },
  { name: "Pasta Primavera" },
  { name: "Spanakopita" },
  { name: "Fried Rice" },
  { name: "Eggplant Parmesan" },
  { name: "Risotto" },
  { name: "Schnitzel" },
  { name: "Yakisoba" },
  { name: "Stuffed Cabbage Rolls" },
  { name: "Khao Soi" },
  { name: "Pulled Pork Sandwich" },
  { name: "Shabu Shabu" },
  { name: "Mapo Tofu" },
  { name: "Hainanese Chicken Rice" },
  { name: "Quiche Lorraine" },
  { name: "Linguine with Clam Sauce" },
  { name: "Caponata" },
  { name: "Kibbeh" },
  { name: "Banoffee Pie" },
  { name: "Chicken Alfredo" },
  { name: "Idli" },
];

export { pantryItems, dishes };
